title: Page

pages:
    hide: false

files: true
    sortable: true

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea

  social:
    label: Social Icons
    type: structure
    style: table
    entry: >
      {{icon}}{{link}}
    fields:
      icon:
        label: Icon
        type: text
      hyperlink:
        label: URL
        type: url
