title: Project

files:
  sortable: true
  type:
    - image
    - video
  width: 1800

pages: false

options:
  template: false
  url: false

fields:
  title:
    label: Title
    type: text
    width: 3/4

  date:
    label: Date
    type: text
    width: 1/4

  coverimage:
    label: Cover Image
    type: image

  text:
    label: Text
    type: textarea
